
PROJECT_DIRS += $(ROOT)/core/fs/uffs/inc
PROJECT_DIRS += $(ROOT)/core/fs/uffs/interface
PROJECT_DIRS += $(ROOT)/core/fs/uffs/interface/spi
PROJECT_DIRS += $(ROOT)/core/fs/uffs/platform/freertos
PROJECT_DIRS += $(ROOT)/core/fs/uffs/src

PROJECT_SOURCEFILES += uffs_spi_drv.c
PROJECT_SOURCEFILES += uffs_os.c
PROJECT_SOURCEFILES += uffs_badblock.c
PROJECT_SOURCEFILES += uffs_crc.c
PROJECT_SOURCEFILES += uffs_ecc.c
PROJECT_SOURCEFILES += uffs_flash.c
PROJECT_SOURCEFILES += uffs_mem.c
PROJECT_SOURCEFILES += uffs_public.c
PROJECT_SOURCEFILES += uffs_version.c
PROJECT_SOURCEFILES += uffs_blockinfo.c  
PROJECT_SOURCEFILES += uffs_debug.c   
PROJECT_SOURCEFILES += uffs_fd.c    
PROJECT_SOURCEFILES += uffs_fs.c     
PROJECT_SOURCEFILES += uffs_mtb.c   
PROJECT_SOURCEFILES += uffs_tree.c
PROJECT_SOURCEFILES += uffs_buf.c        
PROJECT_SOURCEFILES += uffs_device.c  
PROJECT_SOURCEFILES += uffs_find.c  
PROJECT_SOURCEFILES += uffs_init.c   
PROJECT_SOURCEFILES += uffs_pool.c  
PROJECT_SOURCEFILES += uffs_utils.c

