
CFLAGS += -DLV_CONF_INCLUDE_SIMPLE -DLV_LVGL_H_INCLUDE_SIMPLE
MODULES += core/lib/gui/lvgl-7.2/src
MODULES += core/lib/gui/lvgl-7.2/src/lv_core
MODULES += core/lib/gui/lvgl-7.2/src/lv_draw
MODULES += core/lib/gui/lvgl-7.2/src/lv_font
MODULES += core/lib/gui/lvgl-7.2/src/lv_hal
MODULES += core/lib/gui/lvgl-7.2/src/lv_misc
MODULES += core/lib/gui/lvgl-7.2/src/lv_objx
MODULES += core/lib/gui/lvgl-7.2/src/lv_themes
MODULES += core/lib/gui/lvgl-7.2/src/lv_widgets
MODULES += core/lib/gui/lvgl-7.2/src/png_decoder

