
PROJECT_DIRS += $(EMBEDX_ROOT)/core/fs/spiffs/src

PROJECT_SOURCEFILES += spiffs_cache.c
PROJECT_SOURCEFILES += spiffs_check.c
PROJECT_SOURCEFILES += spiffs_driver.c
PROJECT_SOURCEFILES += spiffs_gc.c
PROJECT_SOURCEFILES += spiffs_hydrogen.c
PROJECT_SOURCEFILES += spiffs_nucleus.c
